spring.application.name=cloudflow-tasks
spring.datasource.url=jdbc:postgresql://cloudflow-db.cv6o4e6kmv9s.us-east-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=senhapostgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect